# FMDB 生产环境由平台提供的唯一 classpath 组合。
spark.version=3.3.1
scala.binary.version=2.12
source.directory=lib
ignored.directory=lib2.12
required.jars=spark-sql_2.12-3.3.1.jar,spark-catalyst_2.12-3.3.1.jar,spark-mllib_2.12-3.3.1.jar,spark-enhance-2.6.0-SNAPSHOT.jar,spark-enhance-depends-2.6.0-SNAPSHOT.jar,spark-extensions-2.6.0-SNAPSHOT.jar,sql-common-2.3.0-SNAPSHOT.jar,sql-spark-2.3.0-SNAPSHOT.jar,gdk-db3-3.7.0.jar
excluded.jars=sql-extended-functions-2.3.0-SNAPSHOT.jar
mutually.exclusive.groups=spark-extensions|sql-extended-functions
